//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class fluxo_otica
    {
        public Nullable<decimal> sum_VALOR_PAGO_ { get; set; }
        public Nullable<System.DateTime> DATA_PAGAMENTO { get; set; }
        public string tp_operacao { get; set; }
    }
}
