//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a4f62c_oticaEntities : DbContext
    {
        public db_a4f62c_oticaEntities()
            : base("name=db_a4f62c_oticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_avaliacao_cliente_site> tb_avaliacao_cliente_site { get; set; }
        public virtual DbSet<tb_cargo> tb_cargo { get; set; }
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_controle_entrada> tb_controle_entrada { get; set; }
        public virtual DbSet<tb_desc_funcionario> tb_desc_funcionario { get; set; }
        public virtual DbSet<tb_desc_venda> tb_desc_venda { get; set; }
        public virtual DbSet<tb_despesa> tb_despesa { get; set; }
        public virtual DbSet<tb_estoque> tb_estoque { get; set; }
        public virtual DbSet<tb_falta> tb_falta { get; set; }
        public virtual DbSet<tb_folha_pagamento> tb_folha_pagamento { get; set; }
        public virtual DbSet<tb_fornecedor> tb_fornecedor { get; set; }
        public virtual DbSet<tb_funcionario> tb_funcionario { get; set; }
        public virtual DbSet<tb_jornada> tb_jornada { get; set; }
        public virtual DbSet<tb_login> tb_login { get; set; }
        public virtual DbSet<tb_ponto> tb_ponto { get; set; }
        public virtual DbSet<tb_produto> tb_produto { get; set; }
        public virtual DbSet<tb_salario> tb_salario { get; set; }
        public virtual DbSet<tb_servico> tb_servico { get; set; }
        public virtual DbSet<tb_venda_registro> tb_venda_registro { get; set; }
        public virtual DbSet<fluxo_otica> fluxo_otica { get; set; }
    }
}
