//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_avaliacao_cliente_site
    {
        public int id_avaliacao { get; set; }
        public Nullable<decimal> av_estrutura { get; set; }
        public Nullable<decimal> av_atendimento { get; set; }
        public Nullable<decimal> av_produto { get; set; }
        public Nullable<System.DateTime> dt_avaliacao { get; set; }
    }
}
