//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_venda_registro = new HashSet<tb_venda_registro>();
        }
    
        public int id_cliente { get; set; }
        public string nm_nome { get; set; }
        public string nm_sobrenome { get; set; }
        public string nr_cpf { get; set; }
        public string nr_rg { get; set; }
        public string nr_cep { get; set; }
        public string nm_rua { get; set; }
        public string nr_moradia { get; set; }
        public string nr_telefone { get; set; }
        public string nr_celular { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public string nm_email { get; set; }
        public string ds_sexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_venda_registro> tb_venda_registro { get; set; }
    }
}
