//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_desc_funcionario
    {
        public int id_desc_funcionario { get; set; }
        public int id_funcionario { get; set; }
        public string nr_telefone { get; set; }
        public string nr_celular { get; set; }
        public string nr_cep { get; set; }
        public string nm_rua { get; set; }
        public Nullable<int> nr_moradia { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
