//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_funcionario()
        {
            this.tb_desc_funcionario = new HashSet<tb_desc_funcionario>();
            this.tb_falta = new HashSet<tb_falta>();
            this.tb_folha_pagamento = new HashSet<tb_folha_pagamento>();
            this.tb_jornada = new HashSet<tb_jornada>();
            this.tb_login = new HashSet<tb_login>();
            this.tb_ponto = new HashSet<tb_ponto>();
            this.tb_salario = new HashSet<tb_salario>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_nome { get; set; }
        public string nm_sobrenome { get; set; }
        public string tp_genero { get; set; }
        public string nr_rg { get; set; }
        public string nr_cpf { get; set; }
        public Nullable<System.DateTime> dt_admissao { get; set; }
        public int id_cargo { get; set; }
        public Nullable<int> nr_dependentes { get; set; }
        public System.DateTime dt_nascimento { get; set; }
    
        public virtual tb_cargo tb_cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_desc_funcionario> tb_desc_funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_falta> tb_falta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_folha_pagamento> tb_folha_pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_jornada> tb_jornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_login> tb_login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ponto> tb_ponto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_salario> tb_salario { get; set; }
    }
}
