//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_folha_pagamento
    {
        public int id_folha_pagamento { get; set; }
        public int id_funcionario { get; set; }
        public decimal vl_salario_liquido { get; set; }
        public decimal vl_salario_bruto { get; set; }
        public decimal hr_extra { get; set; }
        public System.DateTime dt_emissao { get; set; }
        public System.DateTime dt_referente_mes { get; set; }
        public decimal vl_decimo_terceiro { get; set; }
        public string tp_cargo { get; set; }
        public decimal vl_vt { get; set; }
        public decimal vl_inss { get; set; }
        public decimal vl_irpj { get; set; }
        public int qtd_falta { get; set; }
        public decimal vl_ferias { get; set; }
        public decimal vl_familia { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
