//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_produto()
        {
            this.tb_controle_entrada = new HashSet<tb_controle_entrada>();
            this.tb_desc_venda = new HashSet<tb_desc_venda>();
            this.tb_estoque = new HashSet<tb_estoque>();
        }
    
        public int id_produto { get; set; }
        public string tp_produto { get; set; }
        public string nm_produto { get; set; }
        public string nm_modelo { get; set; }
        public string nm_cor { get; set; }
        public string nm_marca { get; set; }
        public Nullable<decimal> pr_preco_unidade { get; set; }
        public Nullable<decimal> pr_preco_lote { get; set; }
        public int id_fornecedor { get; set; }
        public Nullable<int> cd_barras { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_controle_entrada> tb_controle_entrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_desc_venda> tb_desc_venda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        public virtual tb_fornecedor tb_fornecedor { get; set; }
    }
}
