//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_servico
    {
        public int id_servico { get; set; }
        public string nm_servico { get; set; }
        public Nullable<decimal> vl_servico { get; set; }
        public string ds_servico { get; set; }
    }
}
