//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.DataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda_registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_venda_registro()
        {
            this.tb_desc_venda = new HashSet<tb_desc_venda>();
        }
    
        public int id_venda { get; set; }
        public decimal vl_venda { get; set; }
        public System.DateTime dt_venda { get; set; }
        public string tp_pagamento { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_desc_venda> tb_desc_venda { get; set; }
    }
}
